// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// subsetCGfiles
CharacterVector subsetCGfiles(StringVector CGFiles);
RcppExport SEXP _methylscaper_subsetCGfiles(SEXP CGFilesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type CGFiles(CGFilesSEXP);
    rcpp_result_gen = Rcpp::wrap(subsetCGfiles(CGFiles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_methylscaper_subsetCGfiles", (DL_FUNC) &_methylscaper_subsetCGfiles, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_methylscaper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
