name: Bioc Check

on:
  pull_request:
    branches:
      - devel

jobs:
  bioc-check:
    runs-on: macos-latest
    name: Bioc Check
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install dependencies
        run: |
          install.packages("BiocManager")
          BiocManager::install("BiocCheck")
        shell: Rscript {0}
      - name: Run BiocCheck
        run: |
          bc_res <- BiocCheck::BiocCheck(args="--no-check-bioc-help")
          n_errors <- length(bc_res$error)
          if (n_errors > 0) {
            message("BiocCheck failed ...")
            quit(status = 1)
          } else {
            message("BiocCheck passed !")
          }
        shell: Rscript {0}
