name: Package Check

on:
  push:
    branches:
      - github-pipelines

jobs:
  package-check:
    runs-on: ubuntu-latest
    name: Check Package Validity
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: release
          use-public-rspm: true

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R Packages
        run: |
          install.packages(c("BiocManager", "devtools"), repos = "https://cloud.r-project.org")
          BiocManager::install("biocthis")
        shell: Rscript {0}

      - name: Run R CMD check
        run: devtools::check()
        shell: Rscript {0}